# Operative
- type: job
  id: SyndicateERTOperative
  name: job-name-syndicate-ert-operative
  description: job-description-syndicate-ert-operative
  playTimeTracker: JobSyndicateERTSecurity
  setPreference: false
  startingGear: SyndicateERTOperativeGear
  icon: "JobIconSyndicate"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  - SyndicateAgent
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplant, DeathRattleImplantCentcomm ]

- type: startingGear
  id: SyndicateERTOperativeGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    back: ClothingBackpackDuffelSyndicate
    shoes: ClothingShoesBootsCombatFilled
    mask: ClothingMaskGasSyndicate
    eyes: ClothingEyesHudSyndicate
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitSyndie
    id: SyndiERTOperativePDA
    ears: ClothingHeadsetAltSyndicateERT
    belt: ClothingBeltMilitaryWebbing
    pocket1: WeaponPistolViper
    pocket2: DoubleEmergencyOxygenTankFilled
  storage:
    back:
    - WeaponDisabler
    - BoxHandcuff
    - MedicatedSuture
    - RegenerativeMesh
    - CrowbarRed
    - MagazinePistol

# Medical
- type: job
  id: SyndicateERTMedical
  name: job-name-syndicate-ert-medical
  description: job-description-syndicate-ert-medical
  playTimeTracker: JobSyndicateERTMedical
  setPreference: false
  startingGear: SyndicateERTMedicalGear
  icon: "JobIconSyndicate"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  - SyndicateAgent
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplant, DeathRattleImplantCentcomm ]

- type: startingGear
  id: SyndicateERTMedicalGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    back: ClothingBackpackDuffelSyndicateMedical
    shoes: ClothingShoesBootsCombatFilled
    mask: ClothingMaskGasSyndicate
    eyes: ClothingEyesHudSyndicate
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitSyndieMedic
    id: SyndiERTMedicalPDA
    ears: ClothingHeadsetAltSyndicateERT
    belt: ClothingBeltMilitaryWebbingMedFilled
    pocket1: WeaponPistolViper
    pocket2: DoubleEmergencyOxygenTankFilled
  storage:
    back:
    - Hypospray
    - MedkitCombatFilled
    - CrowbarRed
    - ChemistryBottleOmnizine
    - ChemistryBottleEpinephrine
    - MagazinePistol

# Lider
- type: job
  id: SyndicateERTLider
  name: job-name-syndicate-ert-lider
  description: job-description-syndicate-ert-lider
  playTimeTracker: JobSyndicateERTLider
  setPreference: false
  startingGear: SyndicateERTLiderGear
  icon: "JobIconSyndicate"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  - SyndicateAgent
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplant, DeathRattleImplantCentcomm ]

- type: startingGear
  id: SyndicateERTLiderGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    back: ClothingBackpackDuffelSyndicate
    shoes: ClothingShoesBootsCombatFilled
    mask: ClothingMaskGasSyndicate
    eyes: ClothingEyesHudSyndicate
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitSyndieCommander
    id: SyndiERTLiderPDA
    ears: ClothingHeadsetAltSyndicateERT
    belt: ClothingBeltMilitaryWebbing
    pocket1: WeaponRevolverPython
    pocket2: DoubleEmergencyOxygenTankFilled
  storage:
    back:
    - WeaponDisabler
    - BoxHandcuff
    - MedicatedSuture
    - RegenerativeMesh
    - CrowbarRed
    - SpeedLoaderMagnum
